### ISSUE TITLE
Stop making automated/spammy pull requests/unsolicited "refactoring" with this tool.

### ISSUE THREAD

**Issue by chexo3** [AlexanderStocks/JavaJanitor#1]
I shouldn't have to tell you this, but opening dozens of pull requests generated by an automated tool without being asked to do so constitutes spam and is evidence of a fundamental lack of knowledge of how to interact with open source projects. Please stop.

**Comment by 0xf24** [comment]
Not only does this constitute as spam, you seem to be expecting free review and labour from various open source projects it's clear you have zero understanding of, for a completely unrelated project (your PHD)

This reminds me of hacktoberfest

**Comment by thatsofia** [comment]
This is platform abuse, which you should be able to report to GitHub.  

Here's a rant because I'm old. 
<details>
I think part of the issue may be the education system for PhDs. I never really understood the appeal of studying PhDs personally - apart from it looking impressive on a resume despite employers looking at your work experience first. The education system can be great for open source but in this case it led to someone experimenting on open source. 
I wonder if colleges could do something like Google's Summer of Code... although mentors and repository orgs/maintainers don't get paid, and it doesn't exactly foster a love for FOSS. Hacktoberfest is worse than GSoC as it's more of a free for all. GSoC had this sort of elitism but GSoC made changes in 2022 to remove the college student requirement! But even then mentors don't get paid, last I checked. The hacktoberfest comparison is rather apt.
</details>
